# Lazygit config
# Keybindings managed by lazygit-keymap-manager.sh
# Mode: CUSTOM (JKLÖ)

gui:
  border: rounded
  sidePanelWidth: 0.4
  theme:
    activeBorderColor:
      - "#5f87af"
    inactiveBorderColor:
      - "#585858"
    searchingActiveBorderColor:
      - "#af875f"
    optionsTextColor:
      - "#005f87"
    selectedLineBgColor:
      - reverse
    inactiveViewSelectedLineBgColor:
      - reverse
    cherryPickedCommitFgColor:
      - "#005f87"
    cherryPickedCommitBgColor:
      - "#d7d7af"
    markedBaseCommitFgColor:
      - "#005f87"
    markedBaseCommitBgColor:
      - "#d7af5f"
    unstagedChangesColor:
      - "#af0000"
    defaultFgColor:
      - default

os:
  open: 'xdg-open'
  editPreset: 'nvim-remote'

keybinding:
  universal:
    prevItem-alt: l
    nextItem-alt: k
    prevBlock-alt: j
    nextBlock-alt: ö
    scrollUpMain-alt1: L
    scrollDownMain-alt1: K
