#!/bin/bash

# Lazygit Keymap Manager
# Manages dynamic keybinding switching for Lazygit
# Integrates with the main vim-keymap-toggle.sh system

LAZYGIT_CONFIG_DIR="$HOME/.config/lazygit"
CONFIG_FILE="$LAZYGIT_CONFIG_DIR/config.yml"
BACKUP_DIR="$HOME/.dotfiles/vim/.vim/lazygit-backups"

# Ensure directories exist
mkdir -p "$BACKUP_DIR" "$LAZYGIT_CONFIG_DIR"

# Function to backup current config
backup_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        local backup_file="$BACKUP_DIR/config-$(date +%Y%m%d-%H%M%S).bak"
        cp "$CONFIG_FILE" "$backup_file"
        echo "Backup: $backup_file"
        return 0
    fi
    return 1
}

# Function to get default HJKL config
get_default_config() {
    cat << 'EOF'
# Lazygit config (Auto-generated by lazygit-keymap-manager.sh)
# Mode: DEFAULT (HJKL)

keybinding:
  universal:
    prevItem-alt: k
    nextItem-alt: j
    prevBlock-alt: h
    nextBlock-alt: l
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
EOF
}

# Function to get custom JKLÖ config
get_custom_config() {
    cat << 'EOF'
# Lazygit config (Auto-generated by lazygit-keymap-manager.sh)
# Mode: CUSTOM (JKLÖ)

keybinding:
  universal:
    prevItem-alt: l
    nextItem-alt: k
    prevBlock-alt: j
    nextBlock-alt: ö
    scrollUpMain-alt1: L
    scrollDownMain-alt1: K
EOF
}

# Function to update config file
update_config() {
    local mode="$1"

    # Backup existing config
    if [[ -f "$CONFIG_FILE" ]]; then
        backup_config
    fi

    # Write new config
    if [[ "$mode" == "custom" ]]; then
        get_custom_config > "$CONFIG_FILE"
    else
        get_default_config > "$CONFIG_FILE"
    fi

    echo "Updated: $CONFIG_FILE"
    return 0
}

# Function to apply keymap mode
apply_keymap_mode() {
    local mode="$1"

    echo "Updating Lazygit keybindings for $mode mode..."

    if update_config "$mode"; then
        if [[ "$mode" == "custom" ]]; then
            echo "Lazygit: CUSTOM (JKLÖ) keybindings activated"
        else
            echo "Lazygit: DEFAULT (HJKL) keybindings activated"
        fi
        echo "Note: Restart Lazygit for changes to take effect"
        return 0
    else
        echo "Failed to update Lazygit config"
        return 1
    fi
}

# Function to show current status
show_status() {
    echo "Lazygit Keymap Status"
    echo "====================="

    echo "Config: $CONFIG_FILE"
    echo "Backups: $BACKUP_DIR"

    if [[ -f "$CONFIG_FILE" ]]; then
        echo "Config file: EXISTS"

        if grep -q "Mode: CUSTOM" "$CONFIG_FILE" 2>/dev/null; then
            echo "Current mode: CUSTOM (JKLÖ)"
        elif grep -q "Mode: DEFAULT" "$CONFIG_FILE" 2>/dev/null; then
            echo "Current mode: DEFAULT (HJKL)"
        else
            echo "Current mode: UNKNOWN (manual config)"
        fi
    else
        echo "Config file: NOT FOUND"
        echo "Current mode: DEFAULT (HJKL) - using Lazygit defaults"
    fi

    local backup_count=$(ls "$BACKUP_DIR"/config-*.bak 2>/dev/null | wc -l)
    echo "Backups: $backup_count"
}

# Function to get mode for status scripts
get_mode() {
    if [[ -f "$CONFIG_FILE" ]] && grep -q "Mode: CUSTOM" "$CONFIG_FILE" 2>/dev/null; then
        echo "Voyager"
    else
        echo "Standard"
    fi
}

# Main script logic
case "${1:-status}" in
    "default")
        apply_keymap_mode "default"
        ;;
    "custom")
        apply_keymap_mode "custom"
        ;;
    "status")
        show_status
        ;;
    "mode")
        get_mode
        ;;
    *)
        echo "Usage: $0 [default|custom|status|mode]"
        echo ""
        echo "Commands:"
        echo "  default - Apply default (HJKL) keybindings"
        echo "  custom  - Apply custom (JKLÖ) keybindings"
        echo "  status  - Show current status"
        echo "  mode    - Output current mode (Standard/Voyager)"
        exit 1
        ;;
esac
