#!/bin/bash

# Neovim Keymap Manager
# Manages dynamic keybinding switching for Neovim
# Integrates with the main vim-keymap-toggle.sh system

NVIM_CONFIG_DIR="$HOME/.config/nvim"
KEYMAPS_FILE="$NVIM_CONFIG_DIR/lua/keymaps.lua"
BACKUP_DIR="$HOME/.dotfiles/vim/.vim/neovim-backups"

# Ensure directories exist
mkdir -p "$BACKUP_DIR" "$NVIM_CONFIG_DIR/lua"

# Function to backup current keymaps
backup_keymaps() {
    if [[ -f "$KEYMAPS_FILE" ]]; then
        local backup_file="$BACKUP_DIR/keymaps-$(date +%Y%m%d-%H%M%S).bak"
        cp "$KEYMAPS_FILE" "$backup_file"
        echo "Backup: $backup_file"
        return 0
    fi
    return 1
}

# Function to get default HJKL keymaps
get_default_keymaps() {
    cat << 'EOF'
-- Neovim Movement Keymaps (Auto-generated by neovim-keymap-manager.sh)
-- Mode: DEFAULT (HJKL)
-- DO NOT EDIT MANUALLY - changes will be overwritten

local M = {}

M.mode = "default"

function M.setup()
  -- Standard HJKL navigation (no remapping needed, this is default)
  -- These explicit mappings ensure consistency across all modes
  vim.keymap.set({'n', 'v', 'o'}, 'h', 'h', { noremap = true, desc = 'Move left' })
  vim.keymap.set({'n', 'v', 'o'}, 'j', 'j', { noremap = true, desc = 'Move down' })
  vim.keymap.set({'n', 'v', 'o'}, 'k', 'k', { noremap = true, desc = 'Move up' })
  vim.keymap.set({'n', 'v', 'o'}, 'l', 'l', { noremap = true, desc = 'Move right' })
end

return M
EOF
}

# Function to get custom JKLÖ keymaps
get_custom_keymaps() {
    cat << 'EOF'
-- Neovim Movement Keymaps (Auto-generated by neovim-keymap-manager.sh)
-- Mode: CUSTOM (JKLÖ)
-- DO NOT EDIT MANUALLY - changes will be overwritten

local M = {}

M.mode = "custom"

function M.setup()
  -- Custom JKLÖ navigation
  -- j = left, k = down, l = up, ö = right
  vim.keymap.set({'n', 'v', 'o'}, 'j', 'h', { noremap = true, desc = 'Move left' })
  vim.keymap.set({'n', 'v', 'o'}, 'k', 'j', { noremap = true, desc = 'Move down' })
  vim.keymap.set({'n', 'v', 'o'}, 'l', 'k', { noremap = true, desc = 'Move up' })
  vim.keymap.set({'n', 'v', 'o'}, 'ö', 'l', { noremap = true, desc = 'Move right' })

  -- Also remap h to something useful (original j = down)
  vim.keymap.set({'n', 'v', 'o'}, 'h', 'j', { noremap = true, desc = 'Move down (original j)' })
end

return M
EOF
}

# Function to update keymaps file
update_keymaps() {
    local mode="$1"  # "default" or "custom"

    # Create backup of existing keymaps
    if [[ -f "$KEYMAPS_FILE" ]]; then
        backup_keymaps
    fi

    # Write new keymaps
    if [[ "$mode" == "custom" ]]; then
        get_custom_keymaps > "$KEYMAPS_FILE"
    else
        get_default_keymaps > "$KEYMAPS_FILE"
    fi

    echo "Updated: $KEYMAPS_FILE"
    return 0
}

# Function to apply keymap mode
apply_keymap_mode() {
    local mode="$1"  # "default" or "custom"

    echo "Updating Neovim keymaps for $mode mode..."

    if update_keymaps "$mode"; then
        if [[ "$mode" == "custom" ]]; then
            echo "Neovim: CUSTOM (JKLÖ) keymaps activated"
        else
            echo "Neovim: DEFAULT (HJKL) keymaps activated"
        fi
        return 0
    else
        echo "Failed to update Neovim keymaps"
        return 1
    fi
}

# Function to show current status
show_status() {
    echo "Neovim Keymap Status"
    echo "===================="

    if [[ ! -d "$NVIM_CONFIG_DIR" ]]; then
        echo "Status: Neovim config not found"
        return 0
    fi

    echo "Config: $NVIM_CONFIG_DIR"
    echo "Keymaps: $KEYMAPS_FILE"
    echo "Backups: $BACKUP_DIR"

    if [[ -f "$KEYMAPS_FILE" ]]; then
        echo "Keymaps file: EXISTS"

        # Detect current mode
        if grep -q 'M.mode = "custom"' "$KEYMAPS_FILE" 2>/dev/null; then
            echo "Current mode: CUSTOM (JKLÖ)"
        elif grep -q 'M.mode = "default"' "$KEYMAPS_FILE" 2>/dev/null; then
            echo "Current mode: DEFAULT (HJKL)"
        else
            echo "Current mode: UNKNOWN"
        fi
    else
        echo "Keymaps file: NOT FOUND"
        echo "Current mode: DEFAULT (HJKL) - using Neovim defaults"
    fi

    # Show backup count
    local backup_count=$(ls "$BACKUP_DIR"/keymaps-*.bak 2>/dev/null | wc -l)
    echo "Backups: $backup_count"
}

# Function to get mode for status scripts (simple output)
get_mode() {
    if [[ -f "$KEYMAPS_FILE" ]] && grep -q 'M.mode = "custom"' "$KEYMAPS_FILE" 2>/dev/null; then
        echo "Voyager"
    else
        echo "Standard"
    fi
}

# Main script logic
case "${1:-status}" in
    "default")
        apply_keymap_mode "default"
        ;;
    "custom")
        apply_keymap_mode "custom"
        ;;
    "status")
        show_status
        ;;
    "mode")
        get_mode
        ;;
    *)
        echo "Usage: $0 [default|custom|status|mode]"
        echo ""
        echo "Commands:"
        echo "  default - Apply default (HJKL) keybindings"
        echo "  custom  - Apply custom (JKLÖ) keybindings"
        echo "  status  - Show current status"
        echo "  mode    - Output current mode (Standard/Voyager)"
        exit 1
        ;;
esac
