#!/bin/bash

# Rider Vim Keymap Manager
# Manages dynamic keymapping switching for Rider's IdeaVim plugin
# Integrates with the main vim-keymap-toggle.sh system

# Rider config location (Windows via WSL2)
IDEAVIMRC_FILE="/mnt/c/Users/FilipM/.ideavimrc"
BACKUP_DIR="$HOME/.dotfiles/vim/.vim/rider-backups"

# Ensure backup directory exists
mkdir -p "$BACKUP_DIR"

# Function to backup current ideavimrc
backup_ideavimrc() {
    if [[ -f "$IDEAVIMRC_FILE" ]]; then
        local backup_file="$BACKUP_DIR/ideavimrc-$(date +%Y%m%d-%H%M%S).bak"
        cp "$IDEAVIMRC_FILE" "$backup_file"
        echo "📁 Backup created: $backup_file"
        return 0
    fi
    return 1
}

# Function to get default HJKL keymapping section
get_default_keymappings() {
    cat << 'EOF'
" ============================================================================
" HJKL Navigation Keymappings (Default Mode)
" ============================================================================
" Tell IdeaVim to handle movement keys in Normal and Visual modes
sethandler h n:vim v:vim o:vim
sethandler j n:vim v:vim o:vim
sethandler k n:vim v:vim o:vim
sethandler l n:vim v:vim o:vim
EOF
}

# Function to get custom JKLÖ keymapping section
get_custom_keymappings() {
    cat << 'EOF'
" ============================================================================
" JKLÖ Navigation Keymappings (Custom Mode)
" ============================================================================
" Tell IdeaVim to handle movement keys in Normal and Visual modes
sethandler j n:vim v:vim o:vim
sethandler k n:vim v:vim o:vim
sethandler l n:vim v:vim o:vim
sethandler ö n:vim v:vim o:vim

" Map to Vim navigation
noremap j h
noremap k j
noremap l k
noremap ö l
EOF
}

# Function to initialize .ideavimrc if it doesn't exist
initialize_ideavimrc() {
    if [[ ! -f "$IDEAVIMRC_FILE" ]]; then
        cat > "$IDEAVIMRC_FILE" << 'EOF'
" IdeaVim Configuration File (~/.ideavimrc)
" Generated by vim-keymap-toggle system for Rider IDE

" ============================================================================
" Basic Settings
" ============================================================================
set number
set relativenumber
set showmode
set incsearch
set ignorecase
set smartcase

" ============================================================================
" IDE-Specific Settings
" ============================================================================
set ideajoin
set ideastatusicon=gray
set idearefactormode=keep

" ============================================================================
" Plugins
" ============================================================================
set surround
set multiple-cursors
set commentary
set argtextobj
set easymotion
set ReplaceWithRegister

" ============================================================================
" Leader Key
" ============================================================================
let mapleader=" "

" ============================================================================
" Navigation Keymappings (will be toggled by vim-keymap-toggle)
" ============================================================================
" Tell IdeaVim to handle movement keys in Normal and Visual modes
sethandler h n:vim v:vim o:vim
sethandler j n:vim v:vim o:vim
sethandler k n:vim v:vim o:vim
sethandler l n:vim v:vim o:vim
EOF
        echo "📝 Initialized new .ideavimrc file"
        return 0
    fi
    return 1
}

# Function to check if keymappings section exists
has_hjkl_mappings() {
    grep -q "sethandler l n:vim v:vim o:vim" "$IDEAVIMRC_FILE" 2>/dev/null && ! grep -q "noremap j h" "$IDEAVIMRC_FILE"
}

has_jklo_mappings() {
    grep -q "sethandler ö n:vim v:vim o:vim" "$IDEAVIMRC_FILE" 2>/dev/null && grep -q "noremap j h" "$IDEAVIMRC_FILE"
}

# Function to update Rider keymappings
update_keymappings() {
    local mode="$1"  # "default" or "custom"

    if [[ ! -f "$IDEAVIMRC_FILE" ]]; then
        echo "❌ .ideavimrc not found at: $IDEAVIMRC_FILE"
        return 1
    fi

    # Backup existing file
    backup_ideavimrc

    # Use Python to manage the ideavimrc file more reliably
    python3 << PYTHON_EOF
import re

try:
    with open('$IDEAVIMRC_FILE', 'r', encoding='utf-8') as f:
        content = f.read()

    # Pattern to find the navigation keymapping section
    # Match sethandler and noremap blocks
    hjkl_pattern = r'sethandler h n:vim v:vim o:vim\nsethandler j n:vim v:vim o:vim\nsethandler k n:vim v:vim o:vim\nsethandler l n:vim v:vim o:vim'
    jklo_pattern = r'sethandler j n:vim v:vim o:vim\nsethandler k n:vim v:vim o:vim\nsethandler l n:vim v:vim o:vim\nsethandler ö n:vim v:vim o:vim'

    if '$mode' == 'custom':
        # Replace HJKL mappings with JKLÖ
        if re.search(hjkl_pattern, content):
            jklo_replacement = 'sethandler j n:vim v:vim o:vim\\nsethandler k n:vim v:vim o:vim\\nsethandler l n:vim v:vim o:vim\\nsethandler ö n:vim v:vim o:vim\\n\\n" Map to Vim navigation\\nnoremap j h\\nnoremap k j\\nnoremap l k\\nnoremap ö l'
            content = re.sub(hjkl_pattern, jklo_replacement, content)
        elif re.search(jklo_pattern, content):
            # Already in custom mode
            pass
        else:
            # Fallback: append custom mappings at the end
            content += '\\n' + '''$get_custom_keymappings'''
    else:
        # Replace JKLÖ mappings with HJKL
        if re.search(jklo_pattern, content):
            # Full pattern with noremap statements
            full_jklo_pattern = r'sethandler j n:vim v:vim o:vim\nsethandler k n:vim v:vim o:vim\nsethandler l n:vim v:vim o:vim\nsethandler ö n:vim v:vim o:vim\n\n" Map to Vim navigation\nnoremap j h\nnoremap k j\nnoremap l k\nnoremap ö l'
            hjkl_replacement = 'sethandler h n:vim v:vim o:vim\\nsethandler j n:vim v:vim o:vim\\nsethandler k n:vim v:vim o:vim\\nsethandler l n:vim v:vim o:vim'
            content = re.sub(full_jklo_pattern, hjkl_replacement, content)
        elif re.search(hjkl_pattern, content):
            # Already in default mode
            pass
        else:
            # Fallback: append default mappings at the end
            content += '\\n' + '''$get_default_keymappings'''

    with open('$IDEAVIMRC_FILE', 'w', encoding='utf-8') as f:
        f.write(content)

    exit(0)

except Exception as e:
    print(f"❌ Error updating keymappings: {e}")
    exit(1)
PYTHON_EOF

    if [[ $? -eq 0 ]]; then
        echo "✅ Updated: $IDEAVIMRC_FILE"
        return 0
    else
        echo "❌ Failed to update keymappings. Rolling back from backup."
        latest_backup=$(ls -t "$BACKUP_DIR"/ideavimrc-*.bak 2>/dev/null | head -1)
        if [[ -n "$latest_backup" ]]; then
            cp "$latest_backup" "$IDEAVIMRC_FILE"
        fi
        return 1
    fi
}

# Function to apply keymap mode
apply_keymap_mode() {
    local mode="$1"  # "default" or "custom"

    if [[ ! -f "$IDEAVIMRC_FILE" ]]; then
        echo "📝 Initializing .ideavimrc for Rider..."
        initialize_ideavimrc
    fi

    echo "🔧 Updating Rider IdeaVim keymappings for $mode mode..."

    if update_keymappings "$mode"; then
        if [[ "$mode" == "custom" ]]; then
            echo "🎯 Rider: CUSTOM (JKLÖ) keymappings activated"
        else
            echo "🎯 Rider: DEFAULT (HJKL) keymappings activated"
        fi
        echo "⚠️  Note: Reload Rider or press Ctrl+Shift+Alt+/ (Help → Find Action) and type 'IdeaVim' to reload config"
        return 0
    else
        echo "❌ Failed to update Rider keymappings"
        return 1
    fi
}

# Function to show current status
show_status() {
    echo "🔧 Rider IdeaVim Integration Status"
    echo "===================================="

    if [[ ! -f "$IDEAVIMRC_FILE" ]]; then
        echo "Status: .ideavimrc not found"
        echo "Path: $IDEAVIMRC_FILE"
        echo "Action: Run 'vimkeys default' to initialize"
        return 0
    fi

    echo "Config file: $IDEAVIMRC_FILE"
    echo "Backup directory: $BACKUP_DIR"

    if has_hjkl_mappings; then
        echo "Current mode: DEFAULT (HJKL)"
    elif has_jklo_mappings; then
        echo "Current mode: CUSTOM (JKLÖ)"
    else
        echo "Current mode: UNKNOWN (manual config)"
    fi

    # Show backup count
    local backup_count=$(ls "$BACKUP_DIR"/ideavimrc-*.bak 2>/dev/null | wc -l)
    echo "Backups available: $backup_count"
}

# Main script logic
case "${1:-status}" in
    "default")
        apply_keymap_mode "default"
        ;;
    "custom")
        apply_keymap_mode "custom"
        ;;
    "status")
        show_status
        ;;
    *)
        echo "Usage: $0 [default|custom|status]"
        echo ""
        echo "Commands:"
        echo "  default - Apply default (HJKL) keymappings to Rider .ideavimrc"
        echo "  custom  - Apply custom (JKLÖ) keymappings to Rider .ideavimrc"
        echo "  status  - Show current Rider IdeaVim integration status"
        exit 1
        ;;
esac
