start-at-login = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
accordion-padding = 30
automatically-unhide-macos-hidden-apps = true
after-startup-command = ['exec-and-forget borders']

[gaps]
inner.horizontal = 40
inner.vertical = 40
outer.left = 40
outer.right = 40
outer.top = 40
outer.bottom = 40

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.example.Convey'
if.window-title-regex-substring = 'Cheat Sheet'
run = 'layout tiling'

[[on-window-detected]]
if.app-id = 'com.example.Convey'
run = 'layout floating'

# Q10 left space (L1) sends ctrl-alt-cmd; holding Shift as well makes it hyper
[mode.main.binding]
ctrl-alt-cmd-j = 'focus left'
ctrl-alt-cmd-k = 'focus down'
ctrl-alt-cmd-l = 'focus up'
ctrl-alt-cmd-semicolon = 'focus right'
ctrl-shift-alt-cmd-j = 'move left'
ctrl-shift-alt-cmd-k = 'move down'
ctrl-shift-alt-cmd-l = 'move up'
ctrl-shift-alt-cmd-semicolon = 'move right'

ctrl-shift-alt-cmd-u = 'join-with left'
ctrl-shift-alt-cmd-i = 'join-with down'
ctrl-shift-alt-cmd-o = 'join-with up'
ctrl-shift-alt-cmd-p = 'join-with right'

ctrl-alt-cmd-1 = 'workspace 1'
ctrl-alt-cmd-2 = 'workspace 2'
ctrl-alt-cmd-3 = 'workspace 3'
ctrl-alt-cmd-4 = 'workspace 4'
ctrl-alt-cmd-5 = 'workspace 5'
ctrl-alt-cmd-6 = 'workspace 6'
ctrl-alt-cmd-7 = 'workspace 7'
ctrl-alt-cmd-8 = 'workspace 8'
ctrl-alt-cmd-9 = 'workspace 9'

ctrl-shift-alt-cmd-1 = 'move-node-to-workspace 1'
ctrl-shift-alt-cmd-2 = 'move-node-to-workspace 2'
ctrl-shift-alt-cmd-3 = 'move-node-to-workspace 3'
ctrl-shift-alt-cmd-4 = 'move-node-to-workspace 4'
ctrl-shift-alt-cmd-5 = 'move-node-to-workspace 5'
ctrl-shift-alt-cmd-6 = 'move-node-to-workspace 6'
ctrl-shift-alt-cmd-7 = 'move-node-to-workspace 7'
ctrl-shift-alt-cmd-8 = 'move-node-to-workspace 8'
ctrl-shift-alt-cmd-9 = 'move-node-to-workspace 9'

ctrl-alt-cmd-slash = 'layout tiles horizontal vertical'
ctrl-alt-cmd-comma = 'layout accordion horizontal vertical'
ctrl-alt-cmd-f = 'layout floating tiling'
ctrl-shift-alt-cmd-f = 'fullscreen'
ctrl-alt-cmd-t = ['flatten-workspace-tree', 'layout tiles horizontal', 'balance-sizes']
ctrl-alt-cmd-minus = 'resize smart -50'
ctrl-alt-cmd-equal = 'resize smart +50'
